### ISSUE TITLE
Data Flow?

### ISSUE THREAD

**Issue by dragonfly90** [UniHousing/UnivHousing#11]
Should we divide the data flow into several parts?

**Comment by jessexu20** [comment]
I think we should finish the dao layer and service layer first and make everyone at the same page.

**Comment by jessexu20** [comment]
I have improved the login parts and will lead to three different path. I think we can separate the task. Should we discuss some time tomorrow? @OliviaHY @dragonfly90 @Expo0911

**Comment by dragonfly90** [comment]
I reserved room 2327 from 7 to 11. Is it  Ok or earlier in the day ?

**Comment by jessexu20** [comment]
I would like to say some time in the afternoon. So that at night, we can separately work on the things instead of wasting a whole day tomorrow.

**Comment by dragonfly90** [comment]
That's Ok for me. We can stay in the graduate room as there is no reserved room

**Comment by jessexu20** [comment]
That's great!

**Comment by OliviaHY** [comment]
Hey sorry I can only do 1:00pm to 3:00pm, is that okay?

2015-03-29 0:23 GMT-04:00 Jesse Xu <notifications@github.com>:
